### PR TITLE
fix the AddIcon color in faq section 

### PR DESCRIPTION
**Pull request by mishra-nikhil0110**
**Please check if the PR fulfills these requirements:**
Now it is visible and the color is chosen according to the theme palette.
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] The code related to the changes has been properly commented

**What kind of change does this PR introduce?** _(select / add custom)_

- (bug | feature | docs | content | chore | breaking change)

**What is the current behavior?** _(link the issue here)_

- Fixes # (issue)
- ...

**What is the new behavior?** _(you can add screenshots or example usage)_

- ...

**Does this PR introduce a breaking change?** _(What changes might users need to make in their application due to this PR?)_

- ...

**Other information:**

### CODE REVIEW

**Review by Panquesito7 — DISMISSED** [review]
Awesome. Thanks! 🚀

**Comment by mishra-nikhil0110** [comment]
Okk got it..

**Review by Panquesito7 — APPROVED** [review]

**Comment by swaroopRajwal** [comment]
got it will review this a bit later

**Comment by swaroopRajwal** [comment]
> undo image **tag** changes, please review🙂

I saw these changes where you used the nextjs Image instead of img tag

you didn't passes height & width to that component or `fill={true}` 

won't it give us build errors ?
have you tried building the application with that nextjs Image changes?

do let me know

if there are no errors you can commit those changes too on this PR or open another :v:

**Comment by mishra-nikhil0110** [comment]
> > undo image **tag** changes, please review🙂
> 
> I saw these changes where you used the nextjs Image instead of img tag
> 
> you didn't passes height & width to that component or `fill={true}`
> 
> won't it give us build errors ? have you tried building the application with that nextjs Image changes?
> 
> do let me know
> 
> if there are no errors you can commit those changes too on this PR or open another ✌️

I will raise a separate PR for the Image tag with all the changes & added height and width or `fill={true}` property.Thanks💡

**Comment by mishra-nikhil0110** [comment]
> > undo image **tag** changes, please review🙂
> 
> I saw these changes where you used the nextjs Image instead of img tag
> 
> you didn't passes height & width to that component or `fill={true}`
> 
> won't it give us build errors ? have you tried building the application with that nextjs Image changes?
> 
> do let me know
> 
> if there are no errors you can commit those changes too on this PR or open another ✌️

Please review changes @swaroopRajwal

**Comment by Panquesito7** [comment]
> > > undo image **tag** changes, please review🙂
> > 
> > 
> > I saw these changes where you used the nextjs Image instead of img tag
> > you didn't passes height & width to that component or `fill={true}`
> > won't it give us build errors ? have you tried building the application with that nextjs Image changes?
> > do let me know
> > if there are no errors you can commit those changes too on this PR or open another ✌️
> 
> I will raise a separate PR for the Image tag with all the changes & added height and width or `fill={true}` property.Thanks💡

It's better to make the updates in the same PR to not create confusion and keep the commit history as well.

**Comment by mishra-nikhil0110** [comment]
> @mishra-nikhil0110 add in the Image tag changes also in this PR Then I'll merge it
> 
> Sorry to keep you waiting for this long I am a bit busy with other work too Thanks for being patient 😀

Please merge this PR if it has no problems, for other issues I will raise a separate PR whenever I get time.
Thank you!

**Comment by swaroopRajwal** [comment]
> > @mishra-nikhil0110 add in the Image tag changes also in this PR Then I'll merge it
> > Sorry to keep you waiting for this long I am a bit busy with other work too Thanks for being patient 😀
> 
> Please merge this PR if it has no problems, for other issues I will raise a separate PR whenever I get time. Thank you!

Done 👍🏻

**Comment by mishra-nikhil0110** [comment]
Hey, 
This PR was for #80, Sorry I forgot to mention. please close the issue #80 .
💡

**Pull request merged**
